### ISSUE TITLE
Replace OpaqueTokens with InjectionTokens to support Angular 5.0

### ISSUE THREAD

**Issue by lafama** [toverux/ngsweetalert2#31]
To produce the below. Upgrade the project to Angular 5.0
Can we have this fixed
```
WARNING in ./node_modules/@toverux/ngsweetalert2/dist/types+es2015-modules/src/di.js
2:31-42 "export 'OpaqueToken' was not found in '@angular/core'
    at HarmonyImportSpecifierDependency._getErrors (/MYPROJECTXXX/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (/MYPROJECTXXX/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (/MYPROJECTXXX/node_modules/webpack/lib/Compilation.js:703:24)
    at Compilation.finish (/MYPROJECTXXX/node_modules/webpack/lib/Compilation.js:561:9)
    at applyPluginsParallel.err (/MYPROJECTXXX/node_modules/webpack/lib/Compiler.js:506:17)
    at /MYPROJECTXXX/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/MYPROJECTXXX/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/MYPROJECTXXX/node_modules/webpack/lib/Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/@toverux/ngsweetalert2/dist/types+es2015-modules/src/di.js
 @ ./node_modules/@toverux/ngsweetalert2/dist/types+es2015-modules/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

**Comment by lafama** [comment]
Seems i had the wrong version. Now it works using 2.0.1
Thank you

**Comment by toverux** [comment]
Indeed, I replaced the OpaqueToken with an InjectionToken in v.2.0.0 :)
